"""add purpose column to users

Revision ID: c2703b669df9
Revises: f6f16f9fa7eb
Create Date: 2026-01-11 00:07:39.137499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2703b669df9'
down_revision: Union[str, Sequence[str], None] = 'f6f16f9fa7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('purpose', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'purpose')
    # ### end Alembic commands ###
