"""removing purpose column to users

Revision ID: f6f16f9fa7eb
Revises: 5e1ebc10e327
Create Date: 2026-01-11 00:06:04.661888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f6f16f9fa7eb'
down_revision: Union[str, Sequence[str], None] = '5e1ebc10e327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'purpose')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('purpose', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
